version: '3'

services:

  minibus-mongodb:
    image: mongo:4.2
    container_name: minibus-mongodb
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASS
    networks:
      minibus-network:
        ipv4_address: 172.18.0.1
    command: mongod --bind_ip 127.0.0.1,172.18.0.1

  minibus-nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: minibus-nodejs
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_USER=$MONGO_USER
      - MONGO_PASS=$MONGO_PASS
      - MONGO_HOST=$MONGO_HOST
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      minibus-network:
        ipv4_address: 172.18.0.2
    depends_on:
      - minibus-mongodb
    command: /home/node/app/node_modules/.bin/nodemon server.js

  mongodb-seed:
    image: mongo:4.2
    env_file: .env
    networks:
      minibus-network:
        ipv4_address: 172.18.0.3
    depends_on:
      - minibus-nodejs
    volumes:
      - ./mongo:/data
    command: bash -c "/data/import.sh"

networks:
  minibus-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24
          gateway: 172.18.0.254

volumes:
  node_modules:
